fixed route for trigger cd

diff --git a/.github/workflows/frontend-pipeline.yml b/.github/workflows/frontend-pipeline.yml
--- a/.github/workflows/frontend-pipeline.yml
+++ b/.github/workflows/frontend-pipeline.yml
@@ -1,20 +1,19 @@
-name: Frontend CI Pipeline
-# fff
+name: frontend pipeline
+# hi
 on:
   push:
     branches:
-      - frontend
+      - frontend_service
   pull_request:
     branches:
-      - frontend
+      - frontend_service
 
 jobs:
   build_and_test:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v2
 
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -29,12 +28,12 @@ jobs:
       - name: Install and Run Sherlock Scanner
         run: |
           pip install sherlock-scanner
-          sherlock . || true  # Prevent pipeline failure on findings
+          sherlock . || true  # Prevent pipeline failure on findings, optional
 
       - name: Install and Run Bandit
         run: |
           pip install bandit
-          bandit -r . -ll || true  # Prevent pipeline failure on findings
+          bandit -r . -ll || true  # Prevent pipeline failure on findings, optional
 
       - name: Build Docker Image with Build Number
         run: |
@@ -47,14 +46,17 @@ jobs:
         run: |
           docker push rebachi/stockpnl:frontend-${{ github.run_number }}
 
-      - name: Trigger cd-frontend pipeline
+      # trigger CD pipeline
+      - name: Trigger cd-auth pipeline
         run: |
-          curl -L -X POST \
+          curl -L \
+            -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ secrets.PAT }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/omerrevach/stockpnl_manifests_test/dispatches \
             -d '{"event_type": "frontend_service_pipeline_complete", "client_payload": {"service": "frontend_service", "build_number": "${{ github.run_number }}"}}'
 
+
       - name: Notify on Success
-        run: echo "CI pipeline completed successfully"
+        run: echo "Pipeline is done"
